# Generated by Django 4.2.7 on 2023-11-26 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auditory_auditory_id'),
        ('users', '0002_user_card_id_user_last_pick'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auditory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.auditory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
