# Generated by Django 4.2.7 on 2023-11-26 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auditory_auditory_id'),
        ('users', '0003_hostorymodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HostoryModel',
            new_name='HistoryModel',
        ),
    ]
