# Generated by Django 4.2.7 on 2023-11-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_hostorymodel_historymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='last_pick',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
