# Generated by Django 4.2.7 on 2023-11-27 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_historymodel_last_pick'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
