# Generated by Django 4.2.7 on 2023-11-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditory',
            name='auditory_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
